exampleSite/content/docs/guide/markdown.md
The existing card for Syntax Highlighting leads to a 404 page, I have replaced it with appropriate link
Closes https://github.com/imfing/hextra/issues/4.
=> fix: card link

.github/workflows/pages.yml
GitHub action responsible for building and deploying the demo site to GitHub Pages.
It modifies the Setup Hugo step (which uses peaceiris/actions-hugo), to use the environment variable `HUGO_VERSION` for specifying `hugo-version`.
In future, you have to update Hugo version only in one place (in `pages.yml`) i.e. environment variable `HUGO_VERSION`.
https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values
=> chore: use environment variable to specify Hugo version

.github/workflows/pages.yml
=> Setup `actions/checkout@v3` to fetch complete Git history

exampleSite/content/docs/guide/shortcodes/steps.md
There needs to be a line break between `{{% steps %}}` and the first H3
If there is no line break between {{% steps %}}  and the first heading, the content is not rendered correctly - example:
=> Line Break Needed Between Steps Shortcode and First Heading

layouts/_default/single.html, layouts/blog/list.html, layouts/shortcodes/card.html
* also enhanced card component a bit
closes #15
=> chore: normalize headings

layouts/shortcodes/card.html
Use `relURL` would break relative path. for example `getting-started` would become `/getting-started`
=> fix: use relURL only for link starts with slash

.github/workflows/pages.yml
https://github.com/actions/checkout#checkout-v4
=> ci: upgrade `actions/checkout` from `v3` to `v4`

layouts/partials/utils/page-description.html
If contents has escape word(like >), description in blog list page show escape for html (like &gt;).
This often occurs on pages that contain source code.
so, add "htmlUnescape" funtion in page-description.html.
=> fix: htmlUnescape page description

layouts/partials/head-css.html
resolve the issue that the browser console complaining about:
```
A preload for 'https://imfing.github.io/hextra/css/compiled/main.min.bc3a9825af59dee550443f0f12871782ccd79449c748f4fc15fee05ce440c174.css' is found, but is not used due to an integrity mismatch.
```
=> fix: add integrity attribute to styles css preload tag

exampleSite/content/docs/guide/organize-files.md, layouts/_default/_markup/render-image.html
* add support for resolving relative sibling images
this would enhance the case in #74 
consider the following structure, `image1.jpg` and `image2.jpg` can only be accessed in `_index.md`
```
content/
├── docs
│   ├── my-page
│   │   ├── content1.md
│   │   ├── content2.md
│   │   ├── image1.jpg
│   │   ├── image2.png
│   │   └── _index.md
```
with this PR, `content1.md` and content2.md` will also be able to reference these images like normal: `![](image1.jpg)`
which will eventually be rendered using relative path `../image1.jpg`
=> feat: enhance image resolving

layouts/blog/list.html
Most users will want to list the most recent posts on their blog.
so, support reverse order using param `params.blog.order: desc`
=> fix: reverse order in blog list page

exampleSite/content/docs/advanced/_index.md, exampleSite/content/docs/advanced/comments.md, exampleSite/hugo.yaml, layouts/_default/list.html, layouts/_default/single.html, layouts/blog/single.html, layouts/docs/list.html, layouts/docs/single.html, layouts/partials/components/comment.html, layouts/partials/components/comments.html, layouts/partials/components/giscus.html
* rename template `comment` to `comments`, same for the settings
* support enable/disable comments on a single page
=> docs: add giscus comments system

assets/js/flexsearch.js, layouts/partials/search.html
fixes #91 
* default to `CTRL K`
* switch to `⌘ K` for macOS/iOS dynamically
=> fix: search shortcut based on user platform

layouts/partials/footer.html
use `<p>` may run into issue when the copyright text contains multiline markdown
=> fix: use div for copyright container in footer

assets/js/back-to-top.js, i18n/en.yaml, layouts/partials/scripts.html, layouts/partials/toc.html
Back to top function function mirroring Nextra's
I'm a little happy with the way Nextra implements this, as they use `opacity` for hiding and showing the button. This means that the back to top button is actually *always* clickable (seriously, go to Nextra and check). But after playing around I see why they made the concession: You have to use `opacity` or the button will *pop* into existence. There is no other way to get that nice fade effect, that I can see.
Anyway, works as intended.
Updated files:
- `toc.html` - Includes the actual button on the page.
- `en.yaml` - Includes i18n specification for `backToTop` so that text can be modified, if desired.
- `scripts.html` - Includes new script file `back-to-top.js` in the splice.
- `back-to-top.js` - VanillaJS functionality for the button. …
=> feat: Back To Top

layouts/partials/components/pager.html
It's related #127
It support empty prev/next pagination.
using by front matter bellow.
```
---
prev: false
next: false
---
```
but I dont know how to solve in blog single page layout.
caused by prev and next are reversed, so many users will be  confused.
=> feat: support empty prev/next pagination

assets/css/compiled/main.css, assets/css/styles.css, exampleSite/content/docs/advanced/customization.md, tailwind.config.js
the primary color saturation can now be overridden via `--primary-saturation` in CSS
closes #102
=> feat: support custom primary saturation

assets/js/back-to-top.js
when the scroll to top element is not present, skip listening to the scroll event
=> fix: skip scroll event if no backToTop element

layouts/shortcodes/callout.html
fixes #140 
the callout now displays correctly with complex markdown contents
=> fix: callout styling issue with markdown content

exampleSite/content/docs/getting-started.md
At present, an info callout (which is part of this PR) appears like this:
All my attempts to fix this went in vain. I observed that there is a leading empty `<p>` tag and trailing empty `<p>` tag within the markup of the shortcode. By markup I am referring to the HTML rendered by the shortcode.
It appears correctly when I delete these empty tags.
Trimming newline characters while processing the Hugo shortcode might be a fix for this.
I realized that the getting-started page looks quite lengthy when the Git submodule docs is added. This can be a bad user experience especially for beginner/new users of Hextra. For a better user experience, I suggest that we split 'Setup Hextra as Hugo module' section and 'Setup Hextra as Git submodule' section to new files (under getting started).
Then we …
=> Add docs for using Hextra as Git submodule, refactor docs for using Hextra as Hugo module

layouts/partials/toc.html
In windows environment, "edit this page" has broken link.
It seems to be broken because the file path separator is different.
linux, mac : https://github.com/test/test/edit/master/a/b/c/index.md
windows : https://github.com/test/test/edit/master/a%5Cb%5Cc%5Cindex.md
so in toc, .File.Path need to be replaced "\\" to "/"
=> fix: broken "edit this page" link in windows

assets/json/search-data.json, exampleSite/content/docs/guide/configuration.md, exampleSite/hugo.yaml, layouts/partials/scripts.html, layouts/partials/utils/fragments.html
add support for different search index types: `content | summary | heading | title`
resolves #139
=> feat(search): support different search index types

exampleSite/content/docs/guide/configuration.md, exampleSite/hugo.yaml, layouts/partials/google-analytics.html, layouts/partials/head.html
and deprecate `site.googleAnalytics`
resolves #171
=> chore: support `services.googleAnalytics.ID`

layouts/partials/toc.html
to prevent markdown headings mess with the output format
e.g.
=> fix: plainify Toc headings

layouts/partials/toc.html
this will fix issues such as `& rendered as &amp;` in TOC because escaping HTML
=> fix: htmlUnescape toc title

layouts/partials/navbar.html, layouts/shortcodes/hextra/feature-card.html
* also fixed broken image link for feature card
Some links for the multi-language site is broken since it's deployed with `/hextra` base URL.
https://imfing.github.io/hextra/zh-cn/
^ for the above site, the navigation bar links are broken because the `{{ .URL }}` for the menu entry will be resolved to `/hextra/<pageRef>`, thus using `{{ .URL | relLangURL }}` would get `/<lang>/hextra/<pageRef>/`
to work around this, we need to use the `{{ .PageRef }}` directly
=> fix: navbar url for multi-lang site

layouts/partials/utils/fragments.html
Fixes #192 
`relref` in the content doesn't break the rendering now:
```
[getting-started]({{< relref "./getting-started" >}})
```
=> fix: ensure relref in search index is properly rendered

layouts/shortcodes/card.html, layouts/shortcodes/cards.html
for use cases such as:
```
{{% steps %}}
This is the second step.
{{< cards >}}
{{< card link="../callout" title="Callout" icon="warning" >}}
{{< card link="/" title="No Icon" >}}
{{< /cards >}}
This is the second step.
This is the third step.
{{% /steps %}}
```
since empty lines will be treated as Markdown thus generating unwanted `<p>` tag that messes up the HTML
=> chore: improve cards compatibility with steps

assets/js/code-copy.js, exampleSite/content/docs/advanced/customization.md, exampleSite/content/docs/getting-started.md, exampleSite/content/docs/guide/shortcodes/details.md, i18n/en.yaml, layouts/_default/_markup/render-codeblock.html
* refactor code copy script to make code copy work within shortcodes
* add translation key for copy code button title
* fix issue when copying from raw pre code block, new lines should be preserved
=> fix: code copy issue for code blocks in shortcode

layouts/partials/sidebar.html
This PR allows pages with `.Params.sidebar.seperator` set to true to act like a separator.
e.g.
```yaml
---
title: Separator-1
weight: 6
sidebar:
separator: true
_build:
render: never
excludeSearch: true
---
```
=> feat: support separator in sidebar

layouts/partials/footer.html
With this PR, the `poweredBy` theme line can be completed overridden:
example `i18n/en.yaml`:
```yaml
poweredBy: test overriding *poweredBy* via `en.yaml`
```
Resolves [comment](https://github.com/imfing/hextra/issues/205#issuecomment-1810707970) in #205
=> feat: allow overriding poweredBy in footer

exampleSite/content/docs/guide/configuration.md, layouts/partials/sidebar.html
now a page can be excluded from the sidebar:
```yaml {filename="content/docs/guide/configuration.md"}
---
title: Configuration
sidebar:
exclude: true
---
```
=> feat: exclude page from sidebar

exampleSite/content/docs/guide/configuration.md, exampleSite/content/docs/guide/configuration.zh-cn.md
The `.Params.editURL` can't find the value when using 
```
---
params:
editURL: "https://"
---
```
in `front matter`. 
It works correctly with
```
---
editURL: "https://"
---
```
=> docs: fix the documentation error about editURL

exampleSite/content/docs/guide/configuration.md
The MR documents the requirement to enable editURL setting.
[A  prior commit](https://github.com/imfing/hextra/commit/04a5c7378a867111e91e3cd6425ed132889a5ad1#diff-5311bf4e1519696010f8298385d9de30210dfcd9dee8785f6deba3a084b62eecL26) the behavior changed from a default of "disable = false" to a default of "enabled = false".
=> fix(docs): add editURL.enable = true

layouts/partials/navbar.html
Mastodon has a feature to display a verified link on your profile. [For this to work a rel="me" attribute has to be set on the link to the mastodon profile. ](https://joinmastodon.org/verification).
This pull request adds the rel="me" attribute to the navbar icon link if the icon is set to "mastodon".
=> chore: add rel="me" attribute to Mastodon navbar icon

exampleSite/content/showcase/index.md
Added [Clever Cloud Documentation website](https://developers.clever-cloud.com) in the showcase page of Hextra site, as suggested [here](https://github.com/imfing/hextra/discussions/259#discussioncomment-8171964). 
Image is hosted in our storage object, to avoid weighing Hextra's site with an additional PNG, but we can relocate it in `/static` if it suits you better.
=> showcase: clever cloud documentation

layouts/partials/head.html
=> chore: add canonical URL to head template

layouts/partials/toc.html
Fix #228 
**Issue:**
In translated Hugo sites, `.File.Path` incorrectly pointed to the root path relative to `content/en`, failing to accurately reference the required subdirectory (`/en`).
**Solution:**
Replaced `.File.Path` with `.File.FileInfo.Meta` for correct root directory referencing. This approach uses the `SourceRoot` attribute from `.FileInfo.Meta` (e.g., `/workspaces/hextra/exampleSite/content/en`), stripping away `BaseDir` and `content` to determine the correct `sourceDir`. 
As a result, `sourceDir` is set to `en` for translated content directories or remains empty for non-translated content.
Example value for `.FileInfo.Meta`:
```
Path:“docs/advanced/comments.md”, 
PathWalk:“docs/advanced/comments.md”, OriginalFilename:"", 
BaseDir:"/workspaces/hextra/exampleSite", …
```
=> fix: accurate `editURL` resolution in translated sites 

layouts/partials/head.html
By adding `canonical` parameter to the front matter and specifying the URL, the canonical URL is added.  If no canonical URL is needed to be specified, the layout will use the current page address for canonical tag. 
Example: 
```
---
title: "Page Title"
description: "Page description"
canonical: "https://canonicalurl.com"
---
=> feat: add canonical to head.html

assets/css/compiled/main.css, assets/css/typography.css
previous pr: https://github.com/imfing/hextra/pull/276 didn't handle the nested list recursively
this PR removes the `first-child` selector so it would apply the `margin-top: 0` recursively for `<li>` elements under `content`
fixes #277
=> fix: clear top margin for nested list recursively

assets/css/compiled/main.css, assets/css/highlight.css, package-lock.json
The padding will be displayed correctly:
fixes #282
=> fix: resolve padding issue for code blocks with filenames but without lang highlight

assets/js/flexsearch.js, exampleSite/hugo.yaml
The default tokenize option 'forward' for flexsearch is good, and have better performance compare with option 'full'. 
**But it can not support some partial search, so i think it may be a good idea to set up a param in `settings.yaml` for user to decide it.** 
Here are the search effect diagrams of two different configurations. The first one with option 'full' can get more results than the second one with option 'forward'.
=> feat: support customize flexsearch tokenize option

layouts/partials/breadcrumb.html, layouts/partials/components/pager.html, layouts/partials/sidebar.html, layouts/partials/utils/title.html
* with graceful fallback to using the directory or filename if no name is provided via the front-matter
Closes #293 
| Before | After |
|:------:|:-----:|
| ![Before](https://github.com/imfing/hextra/assets/5097752/6dc9a3c0-6a52-4bb8-841e-ed9bbd64b621) | ![After](https://github.com/imfing/hextra/assets/5097752/bffdae01-e751-4304-819c-65898e9e25bf) |
=> feat: add title utility to get page or section title

layouts/shortcodes/callout.html
Closes #315 
| Before | After |
|:------:|:-----:|
| ![Before](https://github.com/imfing/hextra/assets/5097752/461aab8d-895a-43cd-8027-41d6081e1a8f) | ![After](https://github.com/imfing/hextra/assets/5097752/ca797827-76a0-4673-851f-61da8b18ae70) |
=> fix: indented callouts rendered incorrectly

layouts/partials/utils/file-path.html, layouts/shortcodes/pdf.html
allow embed pdf files in a page
usage:
```
{{% pdf "dummy.pdf" %}}
```
Example:
=> feat: pdf shortcode (unstable)

exampleSite/hugo.yaml, layouts/blog/list.html, layouts/partials/utils/sort-pages.html
config to sort blog post list page
```yaml
params:
blog:
list:
displayTags: true
sortBy: date
sortOrder: desc # or "asc"
```
=> feat: support sort blog post list page

exampleSite/content/blog/_index.zh-cn.md
I notice that RSS button is missed when switching language to Chinese in the documentation of Hextra. It's added now in this PR, hope it helps.
=> docs(i18n): add zh-cn translation of RSS button

layouts/_default/baseof.html
The js scripts must be in the `<body>`.
=> fix: js scripts not in body element

exampleSite/content/docs/guide/markdown.md
Fix code mistake by making sure backticks are inserted at start and end of example text
=> docs(fix): correct a mistake in markdown guide

layouts/shortcodes/hextra/hero-container.html
On Hextra front-page, there is a lot of unused space on the right side of headline, ideal to insert a logo image.
I created the following `layouts/shortcodes/hextra/hero-container.html` shortcode, implementing a container with optional logo image and related link. Based on my tests, an image with `350px` height will perfectly align with the existing Hextra `badge`, `headline` and `subtile` group.
Visit https://axivo.com/k3s-cluster/.
Example of `hextra/hero-container` shortcode usage, with image pulled from `/static/images` directory:
```
{{< hextra/hero-container
image="images/logo-services.svg"
imageLink="https://github.com/axivo/k3s-cluster"
imageTitle="Kubernetes Services"
>}}
{{< hextra/hero-badge link="https://github.com/axivo/k3s-cluster" >}}
<div class="hx-w-2 hx-h-2 …
```
=> feat: add hextra hero-container shortcode

.github/CONTRIBUTING.md, .github/workflows/pages.yml, layouts/partials/footer.html, layouts/partials/language-switch.html, layouts/partials/sidebar.html, netlify.toml, theme.toml
When running the example site, a deprecation warning is shown:
```
INFO  deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in a future release. Use hugo.IsMultilingual instead.
```
This PR fixes this warning.
=> fix: use `hugo.IsMultilingual` to replace deprecated `.Site.IsMultiLingual`

exampleSite/content/docs/guide/organize-files.md, layouts/partials/breadcrumb.html
Hi there! Hextra is awesome and I wanted to propose a feature that I've found useful recently: **the ability to hide breadcrumbs on specific pages.**
This has been especially useful on "index" pages, for example, where even with a custom `linkTitle` there's just not much value added from the breadcrumb.
I've also included some documentation updates for breadcrumbs in general—and for this `hideBreadcrumbs` option specifically—as I wasn't finding that information elsewhere.
|`/docs`|`/docs/processes/story-points`|
|---|---|
| At my Docs index page (`/docs`), the title `Documentation` being repeated twice by the auto-generated breadcrumbs isn't really helpful. <img width="603" alt="hextra-breadcrumbs-before-A" src="https://github.com/imfing/hextra/assets/875201/c5b36787-28d9-4814-8455-42ee885 …
=> feat: add support for `breadcrumbs` param in front matter for showing/hiding breadcrumbs on specific pages

assets/css/chroma/dark.css, exampleSite/content/docs/guide/markdown.fa.md, exampleSite/content/docs/guide/markdown.md, exampleSite/content/docs/guide/markdown.zh-cn.md
* Added missing MD boxes showing how to define rendered examples.
* Made the emphasis syntax visible when using the dark mode. 
* Fixed a few _markdownlint_ issues.
=> docs: add missing Markdown syntax examples

layouts/partials/head.html
Fix:
```
ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.133.0.
Use .Site.Config.Services.GoogleAnalytics.ID instead.
```
=> fix: remove deprecated google analytics reference in head.html

exampleSite/content/docs/guide/markdown.fa.md, exampleSite/content/docs/guide/markdown.md, exampleSite/content/docs/guide/markdown.zh-cn.md
[Unsplash Source is deprecated and being sunsetted](https://unsplash.com/documentation/changelog#unsplash-source-sunset). There is no longer a way to retrieve a random Unsplash image by URL.
[Lorem Picsum](https://picsum.photos) offers a comparable free image API with URL fetching.
This PR replaces the broken Unsplash links with Lorem Picsum links.
=> docs: update image examples with Lorem Picsum

layouts/_default/list.html, layouts/_default/single.html, layouts/_default/wide.html, layouts/blog/list.html, layouts/blog/single.html, layouts/docs/list.html, layouts/docs/single.html, layouts/index.html
When Title not using from front-matter but from markdown body, <h1> will be displayd twice. 
1 is empty
1 is regular md <h1
=> Bugfix: optional Title in md Head

exampleSite/content/docs/guide/shortcodes/cards.md
The `tag` icon was incorrectly shown in the example as being `warning`, which can be confusing when trying to correlate the two.
=> docs: fix incorrect icon in example

layouts/partials/head-css.html
Deprecated in Hugo [v0.128.0](https://github.com/gohugoio/hugo/releases/tag/v0.128.0).
=> fix: replace deprecated `resources.PostCSS`

assets/js/sidebar.js
Long sidebars did not scroll to show the selected entry. This made working with such long sidebars quite confusing.
QAed using 10+ copies of `exampleSite/content/docs/guide/shortcodes/callout.md`.
Fixes #395
=> feat: scroll selected sidebar entry into view

assets/js/flexsearch.js, assets/json/search-data.json
* Resolve https://github.com/imfing/hextra/issues/469
Shows breadcrumbs instead of the page title for each section of the search results.
For some reason `data` can be incomplete on [our site](https://github.com/netduma/knowledge-base), I need to figure out why exactly.
=> feat: show breadcrumbs in search results

assets/css/compiled/main.css, assets/css/styles.css, exampleSite/content/docs/advanced/customization.md, tailwind.config.js
Lightness is adjusted in a way that `--primary-lightness` becomes the midpoint of the 0-100% range and the calculated result will never go out of that range, it's not a simple addition. 95% lightness is still almost white and 5% is still almost completely black.
This seem to work pretty well with the exception that hextra seem to apply 5% lower lightness in most prominent places (links and buttons), so you need to consistently add +5% lightness to your `--primary-lightness` value but I'm not going to fix that in this PR.
Very high and very low `--primary-lightness` values are not recommended, but they do work.
Something to visualize the algorithm on a 0-100 scale: https://www.desmos.com/calculator/lsdmffszmy (`Y` is base color lightness, `x` is the target lightness)
=> feat: add customizable primary lightness support

assets/json/search-data.json
- this PR reverted the change introduced in #473 which causes a nil pointer dereference issue reported in #478 and https://github.com/imfing/hextra/discussions/481
- will need a reproducible example to investigate the root cause in the future
=> fix: add back empty content filter in search-data.json

layouts/partials/navbar.html, layouts/partials/sidebar.html, layouts/partials/toc.html
This PR fixes the typo in "noreferer". It should be "noreferrer".
=> fix: typo in ref="noreferer"

exampleSite/content/showcase/index.md
Hi,
Thank you for this really nice hugo theme. I would love to add the documentation website of my simulation tool `cellular_raza` to the showcase site.
I was unsure where to put the image so I simply included it in the static folder but I assume that this is not the correct place. Please let me know where to put it.
=> add cellular_raza to showcase exampleSite

layouts/partials/scripts.html
Make mermaid render diagrams on manual toggle between themes, after initial page load.
The original code renders the correct theme only on the initial page load. Toggling to a different theme after initial page load does not change the mermaid theme, which leads to light grey text on white background etc.
=> fix: rerender mermaid diagrams on theme change

layouts/shortcodes/hextra/hero-section.html
On Hextra front-page, I need the ability to insert a `h2` heading, defining additional section titles. For example, adding a subtitle above `hextra/feature-grid`.
I created the following `layouts/shortcodes/hextra/hero-section.html` shortcode, implementing a section.
Visit https://axivo.com/k3s-cluster/.
Example of `hextra/hero-section` shortcode usage, default header size is `h2`:
```
{{< hextra/hero-section >}}
Used Technologies
{{< /hextra/hero-section >}}
```
Example of `hextra/hero-section` shortcode usage, with `h3` header size:
```
{{< hextra/hero-section header="h3" >}}
Used Technologies
{{< /hextra/hero-section >}}
```
Example of `hextra/hero-section` shortcode usage, with `h4` or greater header size:
```
{{< hextra/hero-section header="h4" >}}
Used Technologies
{{< …
```
=> feat: Implement hextra hero-section

layouts/partials/footer.html
Otherwise it adds extra padding to the footer.
=> fix: only display footer switches section if it actually has content

exampleSite/hugo.yaml, layouts/partials/components/giscus.html
To customize your giscus theme, select a theme from [https://giscus.app/](https://giscus.app/) and update the relevant option in the `hugo.yaml` file.
```yaml
params:
comments:
giscus:
theme: noborder_light    #  dark_high_contrast  |  dark_protanopia  |  cobalt  |  etc.
```
---
Related issue #521
=> feat: add giscus theme customization

exampleSite/content/docs/guide/syntax-highlighting.md, layouts/_default/_markup/render-codeblock.html, layouts/partials/components/codeblock.html
This introduces new attribute `filename_uri_base` that adds to codeblock rendering a feature allowing to render a link from the code block title to wherever the sources could be looked up.
UPD: you can see it here: https://deploy-preview-523--hugo-hextra.netlify.app/docs/guide/syntax-highlighting/#link-to-file
=> feat: support link in code block title

layouts/shortcodes/card.html
This PR changes the processing of the given card $image to the more generic [.Process](https://gohugo.io/content-management/image-processing/#image-processing-options) method available from hugo v0.119.0.
It allows to process both global images from assets as well as local/page bundle images.
resolves #103
=> refactor: use generic .Process for card processing and allow bundled images

layouts/shortcodes/card.html
This commit attempts to fix a bug (#549) introduced by switching to Hugo's generic .Process method (see #103).
It skips processing on remote resources and does not process local .svgs either.
=> fix: skip image process on svgs and remote images

assets/js/flexsearch.js
- Added support for CJK (Chinese, Japanese, Korean) languages in FlexSearch encoding.
- Introduced `isCJK` function to detect language and select appropriate encoding method.
- Implemented `encodeCJK` and `encodeDefault` functions for different tokenization strategies.
=> feat: enhance FlexSearch encoding for CJK support

layouts/partials/scripts.html, layouts/partials/scripts/core.html, layouts/partials/scripts/katex.html, layouts/partials/scripts/mermaid.html, layouts/partials/scripts/search.html
This pull request refactors the `layouts/partials/scripts.html` file by moving the script configurations to separate partial files for better modularity and maintainability. The changes include creating new partial files for core scripts, search, Mermaid, and KaTex functionalities.
Refactoring scripts into partial files:
* [`layouts/partials/scripts.html`](diffhunk://#diff-ed3b5a25a9efb89d0cebc442bd8b68c2b2caa45746f6633f89aa4a0e45410f9aL1-L104): Removed inline script configurations and replaced them with calls to newly created partial files.
* [`layouts/partials/scripts/core.html`](diffhunk://#diff-82ead61dd9d44a8d2748e8983dbd7090690826ed0d27ed7f97395a074a007688R1-R14): Added core script configurations including theme, menu, tabs, language, code copy, file tree, sidebar, and back-to-top …
=> refactor: modularize scripts partial into separate components

exampleSite/hugo.yaml, layouts/blog/single.html
This pull request introduces changes to the pagination settings and the layout of the blog articles. The key changes include adding a new configuration for displaying pagination and updating the blog article layout to respect this configuration.
Configuration changes:
* [`exampleSite/hugo.yaml`](diffhunk://#diff-6052113475ce5476ec9e005d96a9de8d43c9031259e77d35d3dcee30117474c1R167-R169): Added a new `article` section with a `displayPagination` parameter to control the pagination display in blog articles.
Layout changes:
* [`layouts/blog/single.html`](diffhunk://#diff-5942e866d871d1df37aadd5f735f37d2708ea0c3ebc753ccd1cc38a71a68e19bL41-R46): Updated the layout to conditionally display pagination based on the new `displayPagination` parameter in the configuration.
=> feat: add optional pagination control for blog articles

layouts/partials/sidebar.html
This pull request includes a small but important change to the `layouts/partials/sidebar.html` file. The change enhances the way titles are processed and displayed in the sidebar by adding additional filters to ensure the HTML is safe and properly unescaped.
* [`layouts/partials/sidebar.html`](diffhunk://#diff-21c3ed4170b0e684f5c718a8b3bb28e73bb15d61a3f0f2301cafcc62ca5034f3L129-R129): Modified the title rendering to use `safeHTML`, `plainify`, and `htmlUnescape` filters for better handling of HTML content.
=> fix: sanitize heading title to prevent html tags displayed on mobile

layouts/partials/sidebar.html
Fixes #593
Correctly parses multilingual URL in sidebar, particularly if lang code follows a nested sub directory.
For instance, GH pages hosting where the baseurl might be of the format `https://<USERNAME>.github.io/<REPO>/`.
This uses the same method the main navbar does for parsing correct lang in URL.
https://github.com/imfing/hextra/blob/662d9202dcca74d66373ac1d1c9071c6ee2533a5/layouts/partials/navbar.html#L37-L40
=> fix: sidebar more menu item link with multilingual

layouts/partials/components/codeblock.html
After looking at the source for the codeblock shortcode and my rendered page, I could only observe this div as difference.
To my own surprise, adding it fixes #605
=> fix: copy-button not being rendered in details blocks

layouts/shortcodes/filetree/container.html, layouts/shortcodes/filetree/folder.html
=> fix: use InnerDeindent for filetree shortcode rendering

exampleSite/content/showcase/index.md
The Clace showcase image got deleted, updated the url
=> docs(showcase): Update Clace image url

layouts/partials/head.html
Currently, the KaTeX CSS file `katex(\.min)?.css` is retrieve from CDN, whose content is not patched:
```css
@font-face {
font-family: KaTeX_AMS;
font-style: normal;
font-weight: 400;
src: url(fonts/KaTeX_AMS-Regular.woff2) format("woff2"),url(fonts/KaTeX_AMS-Regular.woff) format("woff"),url(fonts/KaTeX_AMS-Regular.ttf) format("truetype")
}
// ...
```
On line 5, for example, `fonts/KaTeX_AMS-Regular.woff2` is expanded to `<my-website>/css/fonts/KaTeX_AMS-Regular.woff2`, which is a nonexistent path in the docs website. This PR adds codes to replace these URLs with CDN's paths.
Fix #655.
=> fix: KaTeX fonts are not fetched from CDN

layouts/_default/_markup/render-image.html, layouts/_default/_markup/render-link.html
When the website is configured with `baseURL = "https://example.com/sub-website/"`, the current link render hook will turn `[](/some/link)` to `<a href="https://example.com/some/link"></a>` rather than `<a href="https://example.com/sub-website/some/link"></a>`. A real-world example is [the theme's documentation website](http://imfing.github.io/hextra/docs/guide/configuration/), where a link with a title of `Organize File` will be redirected to the 404 page. This PR fixes this problem. Note that merging this will introduce a breaking change, but I personally think that this makes sense, in that the Hextra theme haven't published a major release ever since.
By the way, in my last PR #657, I mistakenly used `?` for URL fragments. The fix is rather apparent, which is only a one-character …
=> fix: link render hook produces dangling links when base URL has additional segments

layouts/partials/footer.html
Has a fixed width,
But it's not centered.
=> Add centering for custom footers

exampleSite/content/docs/guide/configuration.md, layouts/partials/head.html
This param completely blocks a page or directory from being indexed on Google. Useful for avoiding indexing duplicate content or any other page that shouldn't appear in search results.
- Adjust `head.html` for optional `noindex` param, make default value `false`
- Document use in `configuration.md`. I also modified the Flexsearch section to be explicit about what  "search index" means on different parts of the page.
=> Add page param to block google indexing 

exampleSite/content/docs/guide/organize-files.md, layouts/blog/single.html
Currently, there is no way for authors to choose the order in which `PAGE.PrevInSection` and `PAGE.NextInSection` are ordered for navigation in the footer of a page.
This PR just changes the `reversePagination` input in `layouts/partials/components/pager.html` from being hardcoded to `true`, to being set from the page front matter like so:
```yaml
---
params:
reversePagination: false
---
```
This allows authors to disable this reverse authoring on a per page basis or use the `cascade` front matter to set it on entire page sections.
=> feat: allow authors to set the value of reversePagination in page front matter

layouts/_partials/head.html
Add a space between the dash and site title in `head.html` to fix spacing.
Space was removed around two weeks ago in commit befce4cd9aaa35d98f23b986ba11ff35fa9b91a4 - [link to file diff](https://github.com/imfing/hextra/commit/befce4cd9aaa35d98f23b986ba11ff35fa9b91a4#diff-96dd75a968976edd5e03170268ed9085733f75c3fb24f992ae613c89e6de42dcL15).
=> fix: spacing between title and site title

dev.toml, layouts/_partials/head.html
Currently, an invalid/wrong SRI hash is listed for `katex.css`.
````
<link rel="stylesheet" href="/css/katex.css" integrity="/css/katex.css" crossorigin="anonymous" />
````
This PR fixes that issue.
It also corrects an outdated link I spotted.
=> fix: wrong SRI hash for katex.css

assets/js/tabs.js, layouts/_shortcodes/tabs.html
Problem: Tabs only worked when `page.tabs.sync`: true was configured because the JavaScript relied on the `data-tab-group` attribute, which was only added when sync was enabled.
Modified the tabs shortcode and JavaScript to work in both synced and non-synced modes
=> fix: tab not switching on non-synced mode

layouts/_shortcodes/badge.html, layouts/_shortcodes/callout.html, layouts/_shortcodes/card.html, layouts/_shortcodes/cards.html, layouts/_shortcodes/details.html, layouts/_shortcodes/filetree/container.html, layouts/_shortcodes/filetree/file.html, layouts/_shortcodes/filetree/folder.html, layouts/_shortcodes/hextra/feature-card.html, layouts/_shortcodes/hextra/feature-grid.html, layouts/_shortcodes/hextra/hero-badge.html, layouts/_shortcodes/hextra/hero-button.html, layouts/_shortcodes/hextra/hero-container.html, layouts/_shortcodes/hextra/hero-headline.html, layouts/_shortcodes/hextra/hero-section.html, layouts/_shortcodes/hextra/hero-subtitle.html, layouts/_shortcodes/icon.html, layouts/_shortcodes/jupyter.html, layouts/_shortcodes/pdf.html, layouts/_shortcodes/steps.html, layouts/_shortcodes/tab.html, layouts/_shortcodes/tabs.html
Some of the shortcodes are not fully documented or are missing in the `exampleSite`.
As a first step, I added documentation inside the code.
=> docs: add documentation on all shortcodes

exampleSite/content/docs/guide/configuration.fa.md, exampleSite/content/docs/guide/configuration.ja.md, exampleSite/content/docs/guide/configuration.md, exampleSite/content/docs/guide/configuration.zh-cn.md, exampleSite/hugo.yaml, layouts/_partials/navbar.html, layouts/_partials/theme-toggle.html
The PR is the same as #499 but updated to Tailwind 4 and with some minor changes.
To answer the question about `12`/`24`. (https://github.com/imfing/hextra/pull/499/files#r1874791928)
`12` is the height of the icons/svg inside the theme toggle:
- https://github.com/imfing/hextra/blob/f79bd1a8cf8d5a5df2d3988f2cbbb91a4af072e5/layouts/_partials/theme-toggle.html#L16
- https://github.com/imfing/hextra/blob/f79bd1a8cf8d5a5df2d3988f2cbbb91a4af072e5/layouts/_partials/theme-toggle.html#L18
`24` is the height of the icons/svg inside the navbar:
- https://github.com/imfing/hextra/blob/f79bd1a8cf8d5a5df2d3988f2cbbb91a4af072e5/layouts/_partials/navbar.html#L36
- https://github.com/imfing/hextra/blob/f79bd1a8cf8d5a5df2d3988f2cbbb91a4af072e5/layouts/_partials/navbar.html#L97
Closes #499
Fixes #343
=> feat(navbar): toggle theme inside navbar

assets/js/lang.js, exampleSite/content/docs/guide/configuration.fa.md, exampleSite/content/docs/guide/configuration.ja.md, exampleSite/content/docs/guide/configuration.md, exampleSite/content/docs/guide/configuration.zh-cn.md, exampleSite/hugo.yaml, layouts/_partials/language-switch.html, layouts/_partials/navbar.html, layouts/_partials/theme-toggle.html
Same approach as https://github.com/imfing/hextra/pull/759, but for the language switcher.
This is more complex than the theme toggle because of the transformation computation.
Tested with `rtl` (Farsi) and `ltr` (English), and on desktop and mobile.
I added an item to the example site's navbar to ease the review, as the site is previewed by Netlify.
I also fixed a pre-existing bug with `rtl` on mobile or small screens.
Closes #662
Fixes #654
=> feat(navbar): language switcher

assets/js/theme.js, layouts/_partials/head.html
https://github.com/imfing/hextra/pull/766#issuecomment-3202548065
To reproduce the bug:
1. Set dark mode
2. Refresh the page
3. There is a flash
You can also reproduce it in dark mode by switching quickly between pages.
=> fix(theme-toggle): quick flash (light/dark)

exampleSite/hugo.yaml, layouts/_partials/components/giscus.html
- Fixes the support of the `system` theme
- Fixes theme switching
- Fixes language
- Fixes Giscuss inside the example page `docs/advanced/comments/`
Closes #358
=> fix(giscus): theme and language

assets/js/lang.js, assets/js/switcher-menu.js, assets/js/theme.js, layouts/_partials/scripts/core.html
Fixes https://github.com/imfing/hextra/pull/760#issuecomment-3235750433
<details>
<summary>2 items</summary>
</details>
<details>
<summary>3 items</summary>
</details>
<details>
<summary>4 items</summary>
</details>
I also changed the theme switcher position: now the 2 menus are at the same position on top.
And I handled the resize of the window.
It can be tried by adding this configuration:
```yml
- name: Lang
weight: 8
params:
type: language-switch
- name: theme
weight: 9
params:
type: theme-toggle
```
Tested with RTL/LTR on Desktop and mobile.
=> fix(navbar): menu positions

layouts/_partials/components/analytics/analytics.html, layouts/_partials/components/analytics/matomo.html, layouts/_partials/components/analytics/umami.html
I forgot the `with` and to fill the TODO.
=> fix(analytics): Matomo analytics

layouts/_partials/components/pager.html, layouts/_partials/footer.html, layouts/_partials/sidebar.html, layouts/blog/single.html, layouts/list.rss.xml
Clean up old calls to `.Scratch`
=> chore: replace `.Scratch` with `.Store`

exampleSite/content/docs/guide/configuration.md, layouts/_partials/opengraph.html
The repository [gohugoio/gohugoioTheme](https://github.com/gohugoio/gohugoioTheme) has been archived.
I updated the partials with https://github.com/gohugoio/hugo/blob/v0.149.0/docs/layouts/_partials/opengraph/opengraph.html
I removed the "featured" part as in the previous version.
I also updated the documentation.
=> feat(opengraph): update the partial

docs/hugo.yaml
The field `parent` is duplicated.
Related to https://github.com/imfing/hextra/pull/813/files#diff-d5c956de42afb7f74e802a33282d709f17378a82367268f07ca3f0fa0ec121d0R123
=> fix(docs): menu main duplicate field
