imfing/hextra

layouts/partials/head-css.html
=> fix: missing integrity value in head css

i18n/zh-cn.yaml, i18n/zh-hk.yaml
Add translation of zh-cn and zh-hk
=> i18n: Add translation of zh-cn and zh-hk

exampleSite/content/docs/getting-started.md
=> current instructions show a 404 and pages dont render correctly

layouts/partials/toc.html
=> fix: toc should display headings as is

exampleSite/content/docs/guide/configuration.md
Added documentation to configure footer information
Closes #22
=> Added info to configure footer

exampleSite/content/docs/guide/configuration.md, layouts/partials/footer.html
=> feat: support markdown for copyright text

layouts/_default/baseof.html, layouts/index.html
* chore: enable footer by default
Closes #29
=> chore: make index page container wider

exampleSite/content/docs/guide/configuration.md
I've just put these at the bottom of the file, I trust you to add them in the appropriate sections.
🤍 Amazing template, thanks for making it.
=> Add Configuration for Logo, Favicon.

exampleSite/content/docs/guide/configuration.md
=> docs: add more instruction for customizing favicon

exampleSite/content/docs/guide/shortcodes/tabs.md
https://github.com/imfing/hextra/discussions/46
=> docs: add instruction for using markdown code blocks in tabs

exampleSite/content/docs/guide/shortcodes/cards.md, layouts/shortcodes/card.html
=> fix: use relative url for card link

exampleSite/content/docs/advanced/customization.md, exampleSite/content/docs/guide/shortcodes/tabs.md
Adds documentation to site for discussions:
+ #40 Highlight Code Mixed with Markdown Text in a Different Color
+ #46 Using code in "Tabs" shortcode
=> Website documentation for discussion #40 and #46

assets/css/compiled/main.css, assets/css/components/scrollbar.css, assets/css/styles.css, assets/js/theme.js, exampleSite/hugo_stats.json, layouts/partials/head.html, layouts/partials/search.html, layouts/partials/sidebar.html, layouts/partials/toc.html
| New | Original |
|--------|--------|
| <img height="600" alt="image" src="https://github.com/imfing/hextra/assets/5097752/046cb0ab-7a40-464b-b26a-21d7900bf183" > | <img height="600" alt="image" src="https://github.com/imfing/hextra/assets/5097752/2aa911a0-6e86-4f10-83b4-b337af785be4"> |
also improved the dark mode scroll bar for html elements by adding `color-scheme: dark` to document element style tag:
Original:
=> feat: enhance scrollbar style

layouts/partials/navbar.html
Height/Width swap issue.
fixes #57
=> fix: swap navbar logo width and height

assets/css/compiled/main.css, exampleSite/content/docs/guide/configuration.md, exampleSite/hugo.yaml, exampleSite/hugo_stats.json, layouts/_default/list.html, layouts/_default/single.html, layouts/blog/list.html, layouts/blog/single.html, layouts/docs/list.html, layouts/docs/single.html, layouts/hextra-home.html, layouts/index.html, layouts/partials/footer.html, layouts/partials/navbar.html, layouts/partials/utils/page-width.html, tailwind.config.js
closes: #51 
Default:
Wide:
Full:
=> feat: support wide and full page modes

dev.toml, exampleSite/content/docs/guide/shortcodes/cards.md, layouts/shortcodes/card.html
* use relative url for static images
* mount `assets` directory for development
=> fix: card image not displaying correctly

assets/css/compiled/main.css, exampleSite/content/showcase/index.md, exampleSite/hugo.yaml, exampleSite/hugo_stats.json, layouts/_default/wide.html, layouts/shortcodes/card.html
=> docs: add showcase page

exampleSite/hugo.yaml, layouts/partials/components/giscus.html
* fixed theme switcher issue
* add example settings for giscus
=> fix: giscus theme and language display issues

layouts/_default/baseof.html
=> fix: footer enable flag logic issue

assets/css/compiled/main.css, assets/css/typography.css
=> fix: not-prose p tag inconsistent style

assets/js/code-copy.js, exampleSite/hugo_stats.json, layouts/_default/_markup/render-codeblock.html
=> chore: add code copy button icons in js

assets/js/theme.js, exampleSite/content/docs/guide/configuration.md, exampleSite/hugo.yaml, layouts/partials/footer.html, layouts/partials/head.html, layouts/partials/scripts.html, layouts/partials/sidebar.html
resolves #135 
Light / dark theme can be configured via:
```yaml
theme:
default: system
displayToggle: true
```
=> feat: add option to set default theme and hide toggle button

assets/css/compiled/main.css, assets/css/highlight.css
| Before | After |
|--------|---|
| ![image](https://github.com/imfing/hextra/assets/5097752/a044b7ba-52bd-4fde-a0fd-3eac16a0623c)  | ![image](https://github.com/imfing/hextra/assets/5097752/6d7b4e44-dc06-4510-8c4c-af9d41faa4e2) |
=> fix(style): remove padding for highlighted code

exampleSite/content/docs/guide/organize-files.md
=> docs: add instructions for configuring layouts

assets/css/compiled/main.css, assets/css/components/code-copy.css, assets/css/styles.css
- add backdrop blur to code copy button
resolves #182 
Light:
Dark:
=> fix(style): add backdrop to code copy button

layouts/partials/toc.html
=> fix: correctly set editURL in front-matter

layouts/shortcodes/include.html
this will replace this PR: #184
=> feat: add `include` shortcode

layouts/partials/sidebar.html
@OliverWu515 finds this typo, I help pr this. Hope it helps. The theme helps a lot for our org to build our documents and we find this typo when we use it.
=> typo: fix typos in sidebar.html

assets/css/typography.css
when more than two lines of summary are provided
=> fix: details toggle display issue

assets/css/compiled/main.css, assets/css/typography.css
=> fix: set top margin to zero for nested list

assets/css/compiled/main.css, assets/css/typography.css
This pull request adds styles for the definition list element in the code. It includes changes to the dt and dd selectors to apply specific styles.
closes #223
Preview:
=> feat: add styles for definition list

assets/js/flexsearch.js
the shortcut element is now hidden when there's input
=> chore: improve search bar shortcut display

assets/css/compiled/main.css, package-lock.json, package.json
=> chore(deps): bump npm package versions

exampleSite/content/docs/guide/deploy-site.zh.cn.md, exampleSite/content/docs/guide/shortcodes/callout.zh-cn.md, exampleSite/content/docs/guide/shortcodes/cards.zh-cn.md.md, exampleSite/content/docs/guide/shortcodes/details.zh-cn.md, exampleSite/content/docs/guide/shortcodes/filetree.zh-cn.md, exampleSite/content/docs/guide/shortcodes/icon.zh-cn.md, exampleSite/content/docs/guide/shortcodes/steps.zh-cn.md, exampleSite/content/docs/guide/shortcodes/tabs.zh-cn.md
Update the translation of zh-cn.
=> docs: update zh-cn translation

README.fa.md, README.md, README.zh-cn.md
Add links to different README, so readers can find it easier.
=> docs: add i18n README links

exampleSite/content/showcase/index.md, exampleSite/content/showcase/index.zh-cn.md
[The website of HITSZ OpenAuto](https://hoa.moe) has been online for quite some time.
Based on hextra, we have made quite a few custom designs to fit our needs as well.
I hope this showcase will be a valuable reference for users who would like to use hextra. 🤗
=> docs: add showcase - HITSZ OpenAuto

exampleSite/content/showcase/index.md, exampleSite/content/showcase/index.zh-cn.md
Add AXIVO docs to Hextra showcase.
Link to one of the projects: https://axivo.com/k3s-cluster/
=> chore(showcase): add AXIVO docs

exampleSite/content/showcase/index.md, exampleSite/content/showcase/index.zh-cn.md
Update AXIVO docs image format.
=> chore(showcase): update AXIVO docs image format

layouts/partials/google-analytics.html, netlify.toml
=> fix: remove deprecated site.GoogleAnalytics

exampleSite/content/docs/guide/shortcodes/steps.md, layouts/shortcodes/tab.html, layouts/shortcodes/tabs.html
=> fix: tabs styling in steps shortcode

assets/css/compiled/main.css, assets/css/components/jupyter.css, assets/css/styles.css, layouts/shortcodes/jupyter.html
- import the jupyter css
- improve the styling on the mobile
=> fix: jupyter styling not applied

exampleSite/content/docs/guide/shortcodes/cards.md
=> docs: add `cols` parameter for cards shortcode

exampleSite/content/docs/guide/organize-files.md, layouts/shortcodes/include.html
This PR fixes two typos I spotted in the project.
=> docs: fix typos

exampleSite/content/showcase/index.md
This PR aims to add the website https://installc.org to the Hextra Showcase.
=> docs(showcase): add Install C

layouts/partials/shortcodes/cards.html, layouts/shortcodes/cards.html
=> feat: make cards as partial

exampleSite/content/docs/advanced/customization.md
These are all the classes I could find.
Let me know if they are not meant to be documented as approved customization.
=> docs: add advanced theme customization instruction

exampleSite/content/docs/guide/shortcodes/others.md, exampleSite/layouts/shortcodes/new-feature.html, layouts/partials/shortcodes/badge.html, layouts/shortcodes/badge.html
=> feat: allow icon in badge shortcode

assets/css/compiled/main.css, exampleSite/hugo_stats.json, layouts/shortcodes/tabs.html
=> fix: correct tabs button color on hover in dark mode

exampleSite/content/docs/guide/latex.md, exampleSite/hugo.yaml
=> docs: add instruction for enable and configure passthrough for latex

assets/css/compiled/main.css, exampleSite/hugo_stats.json, layouts/_default/taxonomy.html, layouts/_default/term.html
https://deploy-preview-542--hugo-hextra.netlify.app/tags/
closes #479
closes #93
=> feat: add tags support

exampleSite/content/docs/advanced/customization.md
it has changed https://github.com/imfing/hextra/blob/709a407b2ef72327a6d2991ac7d03dbbbd510a3c/layouts/partials/footer.html#L40C40-L40C56
=> docs fix wrong param footer

layouts/404.html
When we scan a project using this theme, an error appears: 'missing doctype' on the 404 page. This change fixes the issue.
=> Fix missing doctype error on 404 page with htmltest scan

exampleSite/content/docs/guide/configuration.md, exampleSite/hugo.yaml
Added a section to the configuration guide (English only) and annotated the `hugo.yaml` example file.
Fixes #548
=> docs: describe page last modification date

exampleSite/content/showcase/index.md
Thank you for the awesome theme! Adding [Regolith Desktop](https://regolith-desktop.com/) to the showcase!
=> docs(showcase): add Regolith Desktop

exampleSite/content/docs/guide/markdown.md
The shortcode allows image resizing, linking, etc.
=> docs: mention Hugo Figure shortcode

assets/js/menu.js
=> feat: hide navbar on mobile when heading links clicked

exampleSite/content/showcase/index.md
Thanks for building a great theme and community.
This PR adds Clace (an open source app deployment platform) to the showcase
=> docs(showcase): Added Clace to showcase

exampleSite/content/showcase/index.fa.md, exampleSite/content/showcase/index.md, exampleSite/content/showcase/index.zh-cn.md
Hi! Thanks for this great Hugo theme; it has served as a fantastic base for [Beginner Privacy](https://beginnerprivacy.com). This PR adds Beginner Privacy to the showcase.
=> docs(showcase): Add Beginner Privacy

exampleSite/content/docs/guide/configuration.md
Related to: https://github.com/imfing/hextra/discussions/628
=> docs: document configure opengraph image

layouts/_partials/utils/fragments.html
=> fix: search results linking to wrong spot on page

exampleSite/content/docs/getting-started.fa.md, exampleSite/content/docs/getting-started.ja.md, exampleSite/content/docs/getting-started.md, exampleSite/content/docs/getting-started.zh-cn.md
=> docs(getting-started): fix instructions for using git submodule

exampleSite/hugo.yaml
the `relref` doesn't work quite well with site under subpath, switch to `ref` for now.
=> fix(banner): update link formats
